declare const classNames: {
  readonly chatView: "chatView";
  readonly transcript: "transcript";
  readonly userBubble: "userBubble";
  readonly assistantBubble: "assistantBubble";
  readonly toolNotice: "toolNotice";
  readonly errorBanner: "errorBanner";
  readonly errorHint: "errorHint";
  readonly statusStrip: "statusStrip";
  readonly statusLeft: "statusLeft";
  readonly workingIndicator: "workingIndicator";
  readonly resumedNotice: "resumedNotice";
  readonly actions: "actions";
  readonly modeSelector: "modeSelector";
  readonly modeSelect: "modeSelect";
  readonly modeWarning: "modeWarning";
  readonly secondaryButton: "secondaryButton";
  readonly inputRow: "inputRow";
  readonly input: "input";
  readonly sendButton: "sendButton";
};
export = classNames;
