declare const classNames: {
  readonly backdrop: "backdrop";
  readonly dialog: "dialog";
  readonly header: "header";
  readonly title: "title";
  readonly list: "list";
  readonly row: "row";
  readonly rowActive: "rowActive";
  readonly check: "check";
  readonly checkVisible: "checkVisible";
  readonly rowText: "rowText";
  readonly rowName: "rowName";
  readonly rowResolved: "rowResolved";
  readonly divider: "divider";
  readonly customLabel: "customLabel";
  readonly customRow: "customRow";
  readonly customInput: "customInput";
  readonly customButton: "customButton";
};
export = classNames;
