declare const classNames: {
  readonly backdrop: "backdrop";
  readonly dialog: "dialog";
  readonly header: "header";
  readonly title: "title";
  readonly section: "section";
  readonly sectionLabel: "sectionLabel";
  readonly row: "row";
  readonly rowLabel: "rowLabel";
  readonly rowValue: "rowValue";
  readonly meter: "meter";
  readonly meterHead: "meterHead";
  readonly meterPercent: "meterPercent";
  readonly track: "track";
  readonly fill: "fill";
  readonly resets: "resets";
  readonly link: "link";
  readonly toggle: "toggle";
  readonly toggleButton: "toggleButton";
  readonly toggleActive: "toggleActive";
  readonly note: "note";
  readonly behavior: "behavior";
  readonly behaviorTitle: "behaviorTitle";
  readonly behaviorDescription: "behaviorDescription";
  readonly empty: "empty";
  readonly error: "error";
};
export = classNames;
